name: Update data.json

on:
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Update data.json with timestamp
        run: |
          echo "{\"message\": \"Halo dari workflow!\", \"updated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > data.json

      - name: Commit and push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data.json
          git commit -m "Update via workflow at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
